plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dotenv-plugin

service: spotenu-deploy

provider:
  name: aws
  runtime: nodejs12.x 
  stage: v1
  region: us-east-1 

custom:
  webpack:
    webpackConfig: webpack.config.js
    packager: "npm"
    includeModules: true 


functions:
  app:
    handler: src/lambda.handler
    events: 
      - http: ANY / 
      - http: "ANY {proxy+}" 
      - cors: true